#!/usr/bin/env python3
"""Generate src/lib/sn-strings.gen.ts (English UI text -> reviewer Shona) from docs/shona-translation.csv.
Run after scripts/shona-inventory.py. Never hand-edit the generated file."""
import csv, json, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIP = ("out_of_scope", "synthetic", "cue_dictionary", "meaning_distinction")
m = {}
with (ROOT / "docs" / "shona-translation.csv").open(encoding="utf-8") as f:
    for r in csv.DictReader(f):
        en, sn = r["english_source_meaning"], r["reviewer_proposed_shona"].strip()
        if r["category"].startswith(SKIP) or not sn or en in m:
            continue
        m[en] = sn
out = ROOT / "src" / "lib" / "sn-strings.gen.ts"
body = ",\n".join(f"  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}" for k, v in sorted(m.items()))
out.write_text("// GENERATED by scripts/shona-ui-strings.py from docs/shona-translation.csv. Do not edit.\n"
               "// Reviewer Shona: user-supplied proposal, not clinician validated.\n"
               f"export const SN_STRINGS: Record<string, string> = {{\n{body},\n}};\n", encoding="utf-8")
print(len(m), "strings ->", out.relative_to(ROOT))
