#!/usr/bin/env python3
"""Generate src/lib/sn-strings.gen.ts (English UI text -> reviewer Shona) from docs/shona-translation.csv.
Only rows whose overlay entry (docs/shona-review-overlay.csv) has ui_publish=yes reach the UI, so review-only
alternatives never win automatically. Run after scripts/shona-inventory.py. Never hand-edit the generated file."""
import csv, json, pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIP = ("out_of_scope", "synthetic", "cue_dictionary", "meaning_distinction")
with (ROOT / "docs" / "shona-review-overlay.csv").open(encoding="utf-8") as f:
    publish = {o["key"] for o in csv.DictReader(f) if o.get("ui_publish") == "yes"}
ph = lambda s: sorted(re.findall(r"\{\w+\}", s))
m, errors = {}, []
with (ROOT / "docs" / "shona-translation.csv").open(encoding="utf-8") as f:
    for r in csv.DictReader(f):
        en, sn = r["english_source_meaning"], r["reviewer_proposed_shona"].strip()
        if r["category"].startswith(SKIP) or not sn or r["key"] not in publish:
            continue
        if ph(en) != ph(sn):
            errors.append(f"placeholder mismatch: {r['key']}")
        if en in m and m[en] != sn:
            errors.append(f"conflicting Shona for {en!r}: {m[en]!r} vs {sn!r} ({r['key']})")
        m.setdefault(en, sn)
if errors:
    sys.exit("\n".join(errors))
out = ROOT / "src" / "lib" / "sn-strings.gen.ts"
body = ",\n".join(f"  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}" for k, v in sorted(m.items()))
text = ("// GENERATED by scripts/shona-ui-strings.py from docs/shona-translation.csv. Do not edit.\n"
        "// Reviewer Shona: user-supplied proposal, not clinician validated.\n"
        f"export const SN_STRINGS: Record<string, string> = {{\n{body},\n}};\n")
if len(sys.argv) > 1 and sys.argv[1] == "--stdout":
    sys.stdout.write(text)
else:
    out.write_text(text, encoding="utf-8")
    print(len(m), "strings ->", out.relative_to(ROOT))
